language: go

go:
  - 1.6.x
  - 1.7.x
  - 1.8.x
  - 1.9.x
  - 1.10.x

env:
  secure: "ELC4rD8nn2l5T48WYbTfcbwGGBmNxl7LAu05hgx5AB9/KA+oD3oBKIJkZqD512gJ31Gtyla/hG9QOgU7LikfWdpGuJjVILy01ZqtgP5SSKsrTdlln1D5pK1ZyHJNrEPevb3W5PYn9ahHnjKGtpobXj4/E0sCXfRPH67jv9hffYs="

before_install:
    - go get -u github.com/haya14busa/goverage
    - go get github.com/daviddengcn/go-colortext

script:
    - go build
    - if [[ "$TRAVIS_GO_VERSION" =~ ^1\.[2-7]\.[0-9]$ ]]; then go test -v github.com/mattn/anko/vm github.com/mattn/anko/core github.com/mattn/anko/packages github.com/mattn/anko/ast/astutil; else goverage -v -coverprofile=coverage.txt -covermode=atomic ./ast/astutil ./vm ./core ./packages; fi
    - ./t/test.sh
    - ./anko ./_example/scripts/term.ank

after_success:
  - bash <(curl -s https://codecov.io/bash)
